services:
  preprocess:
    build:
      args:
        http_proxy: ${http_proxy}
        https_proxy: ${https_proxy}
        no_proxy: ${no_proxy}
      context: ../
      dockerfile: ./docker/Dockerfile
    command: bash -c '/workspace/docker/preprocess-data.sh'
    environment:
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
      - no_proxy=${no_proxy}
      - PORT=${PORT:-8888}
      - WORKSPACE=/workspace
      - DATA_DIR=/workspace/data
      - OUTPUT_DIR=/workspace/output
      - USER_CONSENT=${USER_CONSENT}
    image: intel/ai-workflows:apollo-anomaly-detection
    privileged: true
    volumes:
      - "${WORKSPACE}:/workspace"
      - "${DATA_DIR}:/workspace/data"
      - "${OUTPUT_DIR}:/workspace/output" 
    working_dir: /workspace/
    stdin_open: true 
    tty: true

