name: "bandit-scan"
run-name: "Bandit Scan"

on: [push]

jobs:
  bandit_job:
    runs-on: [self-hosted, Linux]
    name: Bandit
    container:
      # python:slim includes both Python3 and Bash
      image: cache-registry.caas.intel.com/cache/library/python:slim
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Bandit
        id: bandit
        uses: intel-innersource/frameworks.actions.bandit@v1.3
