name: "bandit-scan"
run-name: "Bandit Scan"

on: [push]

jobs:
  bandit:
    name: Bandit
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Scan
        uses: intel-innersource/frameworks.devops.github.actions.bandit@main
        with:
          scan_path: src
